# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn install --frozen-lockfile
            - run: yarn run build
            - run: yarn run test

            - name: Deploy
              #   if: github.event_name != 'pull_request'
              run: |
                  if [[ -z "${user_name}" ]]; then echo "yes user name" else "no user name" fi
                  if [[ -z "${github_token}" ]]; then echo "yes github token" else "no github token" fi
                  git config --global user.name $user_name
                  git config --global user.email $user_email
                  git remote set-url origin https://${user_name}:${github_token}@github.com/${repository}
                  yarn run deploy
              env:
                  user_name: "chodyo"
                  user_email: "4218016+chodyo@users.noreply.github.com"
                  github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
                  repository: ${{ github.repository }}
